"""Renderer Protocol — 渲染层抽象，REPL 和 TUI 各自实现."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from ..core.agent import AgentEvent
    from ..llm.base import TokenUsage, ToolCall
    from ..tools.base import ToolResult


class Renderer(Protocol):
    """Agent 事件渲染接口."""

    def render_text_delta(self, text: str) -> None: ...
    def render_text_end(self) -> None: ...
    def render_tool_call_start(self, tool_call: ToolCall | None, prefix: str = "  ") -> None: ...
    def render_tool_call_args(self, tool_call: ToolCall | None, prefix: str = "    ") -> None: ...
    def render_tool_result(self, tool_call: ToolCall | None, result: ToolResult | None, prefix: str = "    ") -> None: ...
    def render_subagent_event(self, event: AgentEvent) -> None: ...
    def render_system(self, msg: str) -> None: ...
    def render_error(self, msg: str) -> None: ...
    def render_finish(self, usage: TokenUsage | None) -> None: ...
